include_recipe 'ophymx-workstation::base_packages'
include_recipe 'ophymx-workstation::envy-code-r'
include_recipe 'ophymx-workstation::google-chrome'
include_recipe 'ophymx-workstation::google-talkplugin'
include_recipe 'ophymx-workstation::vala'
