include_recipe 'ophymx-workstation::packages_creative'
include_recipe 'ophymx-workstation::packages_desktop'
include_recipe 'ophymx-workstation::packages_scripting'
include_recipe 'ophymx-workstation::packages_svsm'
include_recipe 'ophymx-workstation::packages_valadev'
