#!/bin/bash

notify() {
  msg=$1
  dbus-send --type=method_call --dest='org.freedesktop.Notifications' \
    /org/freedesktop/Notifications org.freedesktop.Notifications.Notify \
    string:'touchpad-toggle' \
    uint32:1 \
    string:'' \
    string:'' \
    string:"Touchpad $msg" \
    array:string:'' \
    dict:string:string:'','' \
    int32:3000
}

state=$(synclient -l | fgrep TouchpadOff | awk '{print $NF}')
case "$state" in
  0) synclient TouchpadOff=1; notify "Off" ;;
  1) synclient TouchpadOff=0; notify "On"  ;;
esac
