set sw=2 sts=2 et ai
colorscheme desert
set nocompatible
set guioptions-=m
set guioptions-=T
set guioptions-=r

autocmd FileType vala setlocal sw=4
autocmd FileType vala setlocal efm=%f:%l.%c-%[%^:]%#:\ %t%[%^:]%#:\ %m
autocmd FileType make setlocal noexpandtab sw=4
autocmd FileType gtkaml setlocal sw=4
autocmd FileType gtkon setlocal sw=4
autocmd FileType xml setlocal sw=4
autocmd FileType python setlocal sw=4
autocmd FileType xml setlocal foldmethod=syntax

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
