#!/bin/sh

service=xscreensaver

. ../common.sh

mkdir -p "$logdir"

[ -f ~/.xscreensaver-resources ] && xrdb -merge ~/.xscreensaver-resources

exec /usr/bin/xscreensaver -no-splash -log "$logdir/xscreensaver.log"
