#!/bin/bash

SYNERGY_DIR=$HOME/.synergy

exec stunnel \
  -v 3 -c -P '' -f \
  -A $SYNERGY_DIR/stunnel-auth.pem \
  -p $SYNERGY_DIR/stunnel-client.pem \
  -o $SYNERGY_DIR/log/stunnel-client \
  -d localhost:24800 -r $REMOTE_HOST:24800
